#!/usr/bin/python

import datetime
import logging
import os
import sqlite3
import time

from sqlite3 import Error

class Main:
    def __init__(self):
        pass

    def run(self):
        print('Hello World!')


if __name__ == "__main__":
    main = Main()
    main.run()
